[package]
name = "pnmsg"
version = "0.1.0"
authors = ["Olly Swanson"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
crc32fast = "1.3"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
